# Generated by Django 3.0 on 2020-07-26 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20200726_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('Addidas', 'Addidas'), ('Bata', 'Bata'), ('Metro', 'Metro'), ('Nike', 'Nike'), ('Reboke', 'Reboke')], max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Casual shoes', 'Casual shoes'), ('Formal shoes', 'Formal shoes'), ('Sports shoes', 'Sports shoes')], max_length=20),
        ),
    ]
